# Generated by Django 2.0.1 on 2018-03-07 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredominio', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproveedor', models.CharField(max_length=250)),
                ('nombreorganizacion', models.CharField(max_length=250)),
                ('rangoas', models.CharField(max_length=250)),
                ('gradoas', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recomendacion', models.DateTimeField(verbose_name='fecha recomendacion')),
                ('comentario', models.CharField(max_length=200)),
                ('calificacion', models.IntegerField(choices=[(1, '1: Servicio Muy Mal recomendado'), (2, '2: Servicio Mal recomendado'), (3, '3: Servicio Regular'), (4, '4: Servicio recomendado'), (5, '5: Servicio Muy recomendado')])),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccionwsdl', models.CharField(max_length=250)),
                ('direccionip', models.GenericIPAddressField(null=True)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendador.Dominio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendador.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccionip', models.GenericIPAddressField(null=True)),
                ('tipousuario', models.CharField(blank=True, max_length=250)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendador.Servicio'),
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendador.Usuario'),
        ),
    ]
