# Generated by Django 2.0.1 on 2018-03-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominio',
            name='descripciondominio',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
