# Generated by Django 2.0.1 on 2018-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0002_dominio_descripciondominio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombreusuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dominio',
            name='nombredominio',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='gradoas',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombreorganizacion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombreproveedor',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rangoas',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='recomendacion',
            name='comentario',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='direccionwsdl',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
