# Generated by Django 2.0.1 on 2018-03-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0003_auto_20180312_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombreusuario',
        ),
    ]
