# Generated by Django 2.0.1 on 2018-03-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0004_remove_usuario_nombreusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='direccionip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccionip',
            field=models.CharField(default='0.0.0.0', max_length=50),
        ),
    ]
