# Generated by Django 2.0.1 on 2018-03-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0006_auto_20180313_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='direccionip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
