# Generated by Django 2.0.1 on 2018-03-13 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0007_auto_20180313_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipousuario', models.CharField(blank=True, max_length=250)),
                ('descripciontipousuario', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipousuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendador.TipoUsuario'),
        ),
    ]
