# Generated by Django 2.0.1 on 2018-03-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0008_auto_20180313_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dominio',
            name='descripciondominio',
        ),
    ]
