# Generated by Django 2.0.1 on 2018-03-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0009_remove_dominio_descripciondominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='proveedor',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
