# Generated by Django 2.0.1 on 2018-04-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0010_auto_20180313_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calificacion', models.DateTimeField(verbose_name='fecha de calificación')),
                ('calificacion', models.IntegerField(choices=[(1, '1: Servicio Muy Mal recomendado'), (2, '2: Servicio Mal recomendado'), (3, '3: Servicio Regular'), (4, '4: Servicio recomendado'), (5, '5: Servicio Muy recomendado')])),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendador.Servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendador.Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='recomendacion',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Recomendacion',
        ),
    ]
